export const LOGIN_REQUEST_SENT = "LOGIN_REQUEST_SENT";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";

export const LOGOUT_REQUEST_SENT = "LOGOUT_REQUEST_SENT";
export const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS";
export const LOGOUT_REQUEST_FAIL = "LOGOUT_REQUEST_FAIL";

export const GET_WAREHOUSSE_DATA = "GET_WAREHOUSSE_DATA";
export const GET_WAREHOUSSE_DATA_RECIEVED = "GET_WAREHOUSSE_DATA_RECIEVED";
export const GET_WAREHOUSSE_DATA_FAIL = "GET_WAREHOUSSE_DATA_FAIL";

export const CHANGE_WAREHOUSE_STATUS_START = "GET_WCHANGE_WAREHOUSE_STATUS_STARTAREHOUSSE_DATA";
export const CHANGE_WAREHOUSE_STATUS_SUCCESS = "CHANGE_WAREHOUSE_STATUS_SUCCESS";
export const CHANGE_WAREHOUSE_STATUS_FAIL = "CHANGE_WAREHOUSE_STATUS_FAIL";

export const FETCH_CLIENT_START = "FETCH_CLIENT_START";
export const FETCH_CLIENT_SUCCESS = "FETCH_CLIENT_SUCCESS";
export const FETCH_CLIENT_FAIL = "FETCH_CLIENT_FAIL";

export const FETCH_ENQUIRY_LIST_START = "FETCH_ENQUIRY_LIST_START";
export const FETCH_ENQUIRY_LIST_SUCCESS = "FETCH_ENQUIRY_LIST_SUCCESS";
export const FETCH_ENQUIRY_LIST_FAIL = "FETCH_ENQUIRY_LIST_FAIL";

export const FETCH_LEAD_LIST_START = "FETCH_LEAD_LIST_START";
export const FETCH_LEAD_LIST_SUCCESS = "FETCH_LEAD_LIST_SUCCESS";
export const FETCH_LEAD_LIST_FAIL = "FETCH_LEAD_LIST_FAIL";
